OctopusDeploy/Library

- step-templates/F5-Disable-Member-Wait-for connections-to-drop.json
Requires the iControlSnapIn installed on the tentacle and registered.
> F5 - Disable Node, wait for connections to drop

- step-templates/netscaler-adc-enable-or-disable-service.json
New step template, allowing to disable/enable a LB service in Citrix NetScaler. The template has no dependencies besides powershell v3+.
> Disable/enable a Citrix NetScaler ADC load balancing service.

- step-templates/redgate-create-database-release.json
- step-templates/redgate-deploy-from-database-release.json
- step-templates/redgate-deploy-from-database.json
- step-templates/redgate-deploy-from-package.json
- includes a step template "Create Database Release"
- includes a step template "Deploy from Database"
- includes a step template "Deploy from Database Release"
- includes a step template "Deploy from Package"
> added first version of Redgate - SQL Release step templates

- step-templates/redgate-create-database-release.json
- step-templates/redgate-deploy-from-database-release.json
- step-templates/redgate-deploy-from-database.json
- step-templates/redgate-deploy-from-package.json
> changed the support e-mail for SQL Release step templates

- step-templates/file-system-create-file.json
I've added a simple step that allows you to create an empty file within the file system.
> Added 'File System - Create File' custom step.

- step-templates/teamcity-download-artifact.json
This is a proposed Step Template to easily download a TeamCity artifact as part of the deployment process.  TeamCity configurations are broken out into individual parameters so they can easily be shared across projects, process steps, etc.
Happy to hear your thoughts and discuss further, thanks!
> Created teamcity-download-artifact.json

- step-templates/umbraco-v7-folder-permissions.json
Octopus step to setup folder permissions for an Umbraco v7 site after
deployment
> Folder permissions in Umbraco v7

- step-templates/windows-certificate-grant-read-access.json
Created a template for granting a user read access to a certificate.
> Add template that grants a user read access to a certificate

- step-templates/hyponome-test-step.json
This is just to use a test for the merging through Hyponome
> Test step template

- step-templates/aws-deregister-elb-instance.json
- step-templates/aws-register-elb-instance.json
- step-templates/aws-register=elb-instance.json
This pull includes a deregistration and registration script that we have been using successfully to remove an instance from an ELB and re-adding it after deployments complete.
> Adding AWS ELB registration templates

- step-templates/file-system-create-folders.json
Added a step template to allow the creation of multiple folders at once
> Added a step template to allow the creation of multiple folders at once

- step-templates/com-component-register.json
- step-templates/com-component-unregister.json
Added a new step templates to register and unregister COM objects using regasm.
> Added a new step templates to register and unregister COM using regasm

- step-templates/amazon-s3-upload.json
This step template allows you to upload files and folders to an Amazon S3 bucket as part of your deployment process.
> Added Amazon S3 Upload step template

- step-templates/F5-Disable-Member-Wait-for connections-to-drop.json
Adding support for customizing protocols for the application in the "IIS Application - Create" template. Fixes issue #138
> Support for EnabledProtocols

- step-templates/web-deploy-publish-website-msdeploy.json
Ive added the ability for people to skip certain folders during deployment. 
Ive also added some info on what all the changes were for that deployment.
> WebDeploy: Added ability to skip certain folders during deployment

- step-templates/iis-app-remove.json
Step template to remove an IIS application.
> IIS Application  - Remove

- step-templates/sql-smo-create-login-and-user.json
Taking inspiration from the step templates to create a database using SMO I modified our existing step that created logins and users with the execute sql template to instead use SMO, making for a much cleaner step in our deployment process.
> Step template for creating login and user in Microsoft SQL Server using SMO

- step-templates/http-test-url.json
Password parameter is single-line text box. Can't get it to work as sensitive/password box :(
> Added support for Basic auth in http-test-url

- step-templates/windows-add-users-to-local-groups.json
Added a step template to allow users to be added to local groups in bulk.
> Added a step template to allow users to be added to local groups in bulk.

- step-templates/windows-create-eventsource.json
I've added new step template, this allows you to create new event source on target computer. Additionally, it allows you to specify custom log name too, if necessary.
It uses exceptions to test for "does the source already exists", as that is the most efficient way.
> Added new step template for creating Windows event sources safely.

- step-templates/rabbitmq-notify-deploy.json
This is the first step if you wish to create a ELK server to have some insight of your deployments.
http://www.eltuko.net/keep-track-of-octopus-deploys-with-the-elk-stack/
> Added step to notify deployment info to rabbitmq.

- step-templates/jasper-clear-cache.json
The web tier has caching enabled, so when we deploy new jasper reports,
we need to clear the web tier cache
> Add clear Jasper web cache

- step-templates/pause-resume-pingdom-check.json
This step template enabled you to pause a single Pingdom check during deployment and enable afterwards.
> Added step template for pause/resume Pingdom check

- step-templates/unicorn-sync-configuration.json
A Unicorn sync script to allow syncing of Sitecore items during deployment.
> Added Unicorn - Sync Configuration step template.

- step-templates/azure-blob-storage-upload.json
Upload files in a directory to a specified Azure Storage blob container.
> Azure Blob Storage Upload template

- step-templates/sharepoint-solution-deployment.json
Deploy the SharePoint Solution using Octopus now.
The Nuget package will contain the .WSP files and this step will deploy the solution on SharePoint farm.
> added the sharepoint-solution-deployment.json for SharePoint

- step-templates/hockeyapp-upload-mobile-app.json
Licensed Apache 2.0 with written permission from Viewpoint inc.
I'm happy to take further feedback and make tweaks.
This script completes our TFS based automation from building Xamarin apps, pushing to Nuget, and finally using Octopus Deploy to publish them to our QA team in Hockey App.
Thanks for the excellent deployment system!
> Added step template to upload apps to Hockey App

- step-templates/windows-scheduled-task-create.json
Updated Windows-Scheduled-Task-Create script to support specifying password on task creation.
Updated Windows-Scheduled-Task-Create to fix bug relating to interval parameter based on Schedule parameter.
> Update Windows-Scheduled-Task-Create to support password parameter

- step-templates/sentry-release-tracking.json
Added step template for notifying sentry of a new release, and optionally resolve all open issues.
> Sentry release tracking

- step-templates/http-post-form.json
Add a new step template to handle simple form posting in standard
x-www-form-urlencoded format to a specified URI.
> Add HTTP - Post Form step template

- step-templates/windows-ensure-hosts-file-entries-exist.json
Created a new template based on an existing one that supports multiple host name entries for a single IP rather than creating 1 for each hostname.
> Created a new template based on the existing Windows hosts file entries step template

- step-templates/variables-substitute-in-files.json
Now works with 3.0 and uses Octostache dll to do the dirty work
> Update Variables - Substitute in Files template

- step-templates/iis-change-app-offline-online.json
Change app_offline.htm to online vice versa with custom variables to setup the file names.
> IIS change app online offline

- step-templates/sentry-release-tracking.json
Avoids crashing when the release already exists, only applies any issues-resolving.
> updated the script for sentry-release-tracking.

- step-templates/ssis-deploy-ispac-from-package.json
I created a step template for deploying SSIS ISPAC projects to MS SQL Server from a package.
> New step template for deploying SSIS ISPAC to MS SQL Server

- step-templates/readyroll-deploy-database-package.json
* Create readyroll-deploy-database-package.json
* Contains a new step template to deploy database packages produced by ReadyRoll
* Adds input boxes for fields like DatabaseName/DatabaseServer
* Removes the need for users to define custom variables
> Add Step Template: ReadyRoll - Deploy Database Package 

- step-templates/xamarin-testcloud-execute-testrun.json
This step template runs a powershell script to upload, create, and execute a Xamarin TestCloud test run from app artifacts in a Nuget package.
> Added step template for Xamarin TestCloud test run

- step-templates/ssrs-report-backup
Created a new Powershell step to back up SSRS reports from a SQL Server SSRS instance
> Created powershell step to backup SSRS reports

- step-templates/newrelic-complete-deployment.json
1. Removed Account Id. It is not required or consumed by the API
2. Replaced HTTP Web Request code with `Invoke-RestMethod` Powershell command
MSDN Invoke-RestMethod
https://technet.microsoft.com/en-us/library/hh849971.aspx
NewRelic Deployment Notification API
https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/deployment-notifications#api
> Update New Relic - Create Deployment to use Invoke-RestMethod

- step-templates/sql-execute-script-file.json
The template use SQL script files to execute the content as SQL
> Add a template to execute SQL files.

- step-templates/application-insights-annotate-release.json
This step will annotate the release into Application Insights.
> Added Application Insights - Annotate Release script step

- step-templates/pagerduty-open-maintenance-window.json
Open a new maintenance window for the specified services.
No new incidents will be created for a service that is currently in
maintenance.
> New template PagerDuty-OpenMaintenanceWindow

- step-templates/http-test-url.json
Add an option to make the http request passing windows authentication
> Add windows authentication to http-test-url

- step-templates/sql-restore-database.json
Relocate files base on the SQL Server configuration.
> Relocate files base on the SQL Server configuration.

- step-templates/splunk-log-event-collector
Adds a new template for the Splunk [HTTP Event Collector](http://dev.splunk.com/view/event-collector/SP-CAAAE6M).
> New template for Splunk Event Collector

- step-templates/teamcity-pin-build-and-dependencies.json
I forgot to add the last modified date and by fields, perhaps this could be merged?
> Added credits

- step-templates/iis-app-create.json
Now handles different app-pool users
Fixed bugs noted here: https://library.octopusdeploy.com/step-template/actiontemplate-iis-application-create
Also added paramenters to make its UI a closer match to _IIS web site and application pool_  deployment feature.
> Modified iis-app-create to handle different app-pool users

- step-templates/iis-website-add-windows-auth-providers.json
Clears all of the the Windows Authorization providers, and then explicitly adds the ones provided.
> Add IIS Website Windows Authoriztion providers

- step-templates/Azure-Contianer-Copy-to-another-Container.json
Add a new step to copy entire containers from one to another. Supports sub folders in containers as well.
> Add a new step to copy Azure blob storage containers

- step-templates/ghostinspector-runsuite.json
Quick but useful step template to automatically run automated UI tests using https://app.ghostinspector.com/.
> Add GhostInspector automation test runner step template

- step-templates/teamcity-pin-build-and-dependencies.json
2 step templates included here, one for the Content Purge API v2 and one for the Fast Content Purge API v3
> Akamai Content Purge step templates

- step-templates/sitecore-unicorn-sync.json
New step template based on this blog post: http://www.sitecorenutsbolts.net/2016/03/14/Octopus-Deploy-Step-for-Unicorn-Sync/
> New step template for Sitecore Unicorn sync

- step-templates/redgate-create-database-release.json
- step-templates/redgate-deploy-from-database-release.json
- step-templates/redgate-deploy-from-database.json
- step-templates/redgate-deploy-from-package.json
We have just released DLM Automation which updates the name of the PowerShell module that these step templates use. This PR updates all references to the old name so the step template will work with the latest versions.
> Update to module name SQLRelease -> DLM Automation

- step-templates/xml-transform-using-xdt.json
This script is used to transform XML file using [XDT](https://msdn.microsoft.com/en-us/library/dd465326(v=vs.110).aspx).
It is adapted from [this script](https://gist.github.com/sayedihashimi/f1fdc4bfba74d398ec5b).
> Add step-template that transform xml using xdt

- step-templates/iis-website-set-log-format.json
the old script assumed 
if ($OctopusParameters['Date']) 		    
would be a valid test to test if a parameter checkbox was checked, which it isn't. Replacement is 
if ($OctopusParameters['Date'] -eq "True") 		   
Only affecting iis <v8
> fixed error in parameter parsing.

- step-templates/newrelic-complete-deployment.json
Uses the newer API, the old one seems to be down.
Needs JSON data for the post.
> Update New Relic Complete Deployment step template

- step-templates/slack-notify-deployment.json
> Include tenant name in slack messages.

- step-templates/http-test-url.json
Add optional test of content returned from request
> Add content checking

- step-templates/elmahio-notify-deployment.json
Created a new step template for notifying [elmah.io](https://elmah.io) on new deployments on Octopus Deploy.
> Added step template for notifying elmah.io about a deployment on Octopus

- step-templates/elmahio-notify-deployment.json
Sorry. Forgot about a name matching the other templates.
> Changed name to correspond with other templates

- step-templates/azure-upload-files.json
The step was quite messy and wasn't run at all.
- I removed the use off OctopusParameters array
- I removed an unused variable
- The Set-AzureStorageBlobContent was false it doesn't contains recurse parameter. Now i remove the whole loop and use the Get-ChildItem to upload the folder content.
> Fix step template

- step-templates/yams-upload.json
https://github.com/Applicita/YamsUploader
https://github.com/Microsoft/Yams
> Added step template for YAMS Uploader

- step-templates/iis-list-sites.json
This step was failing for me on some of my older servers due to the WebAdministration module not being available to the Powershell script.  The code added here was taken from Calamari.
> Adding Import-Module & Add-PSSnapIn WebAdministration logic to iis-list-sites

- step-templates/configuration-encrypt-web-config-section.json
> other files and web.config can be contained in different paths

- step-templates/microsoft-teams-post-a-message.json
During our deployments we sometimes encountered timeouts when executing this step. I therefore added the ability to specify a custom timeout.
> Added the option to specify a custom timeout for the web request

- step-templates/windows-create-eventsource.json
Made a change to way the script template checks for an already existing event source. The check is now more explicit, which makes it better performing and language independent
> Made a change to way the script template checks for an already existing event source

- step-templates/microsoft-teams-post-a-message.json
Fixed a bug that could result in an error in case a non-integer timeout was specified
> Fixed a bug that could result in an error in case a non-integer timeout was specified

- step-templates/clickonce-from-deployed-package.json
Update package creation to handle:
- Allow ClickOnce feature for client update in case of new package version
- custom package icon display
> Update Create Click-Once from deployed package step template

- step-templates/file-download.json
Download a file url to a file destination path
> Create file download step

- step-templates/nssm-windows-service-create.json
Adding template to create Windows Service using NSSM (Non-Sucking Service Manager) 
More information here: https://nssm.cc/
Beneficial for hosting portable apps such as dotnet core APIs to avoid dependency on standard .NET library.
> Template to create Windows Service using NSSM

- step-templates/octopus-import-certificate.json
Create or replace an [Octopus Certificate](https://octopus.com/docs/deploying-applications/certificates) from a certificate file
> Octopus - Import Certificate

- step-templates/file-system-rename-file.json
Adds a step template for renaming files on the file system.
> File System - Rename File

- step-templates/variables-substitute-in-json-file.json
Use this step template after the Deploy API step template to
substitute variables in a target json file like appsettings.json
with Octopus scoped variables. Currently supported data types
are string, boolean, interger, decimal and non-empty string arrays and can replace 
these types inside nested types as well as long as you name them like 
prop:subprop:subsubprop (like AppMetrics:GlobalTags:env)
this should be enough for most of the needs for files like
appsettings.json
* Are all parameters in the template consistent with the examples here, …
> Variables - Substitute in Json file

- step-templates/sql-deploy-dacpac.json
Fixes OctopusDeploy/Library#541
> Add parameter for specifying SQL Server version of target database

- step-templates/network-add-ssl-certificate-binding.json
> Added step template to allow SSL certificate binding using NETSH

- step-templates/iis-apppool-update-recycle-settings.json
> Added ability to clear settings from recycling in IIS

- .gitignore
- tools/StepTemplatePacker/scripts/Get-OctopusStepTemplateFileType.ps1
This patch fixes unpacking and packing all step templates and adds the .ps1 and .sh files that are created to the .gitignore file.
> Fixed unpacking all the step templates.

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add note about prefixing parameter names

- step-templates/variables-substitute-in-files.json
> Improve help text for the parameters

- step-templates/teamcity-run-build.json
> Adding step template for running a build in TeamCity

- step-templates/windows-grant-logon-as-service.json
Step template to allow accounts to be granted SeServiceLogonRight as part of a deployment.
> Adds Grant Logon As Service Step Template

- step-templates/azure-create-new-resourcegroup.json
- step-templates/azure-create-new-webapp.json
Updated azure-create-new-resourcegroup.json.
Added:
New Idmepotency steps
Error handling
Helptext for "Azure Account" to make it more obvious what this is for.
Updated:
Variable name for "Name" to the more unique "ResourceGroupName"
Template name to set convention for more step templates. Restricted due to max character length in OD.
Newer format for later version of OD.
Created new step template to create Azure Web Apps.
> Update Azure Step template and add new step template

- step-templates/aws-add-tags-to-ec2-instance.json
- step-templates/aws-change-ec2-instance-state.json
- step-templates/aws-create-a-route-53-resource-record.json
- step-templates/aws-create-a-security-group.json
- step-templates/aws-launch-ec2-instance.json
- step-templates/octopus-wait-for-deployment-target-registration.json
> Add step to launch single EC2 Instance and companion step to detect new deployment target

- step-templates/windows-scheduled-task-enable.json
So that you can choose a variable as value.
* Are you happy to contribute your template under …
> Added ControlType for TaskName

- step-templates/windows-scheduled-task-disable.json
So that it allows for Variable selection.
* Are you happy to contribute your template under …
> Added ControlType for the TaskName

- step-templates/Jenkins-Queue-Job.json
Adding support for username and password.    
Change the check of the job to be of the created job and not the latest
This allow multiple jobs to run in paralel
> Adding support for username and password.

- step-templates/azure-add-or-update-azure-loadbalancer-health-probe.json
- step-templates/azure-add-or-update-azure-loadbalancer-rule.json
> Azure load balancer rule and health probe templates

- step-templates/windows-check-net-core-framework-version.json
It should detect asp.net core module if it comes from bundle installer
> Fix regex to detect correctly asp.net core module

- step-templates/akamai-cpcode-fastpurge.json
> Adding step template to fast purge via CPCode

- step-templates/windows-add-poll-endpoint-task.json
> Adding "Windows - Add poll rest endpoint scheduled task" deploy step

- web.config
> Add HTTPS redirect rule

- step-templates/azure-create-new-resourcegroup.json
Changed the Powershell script to a simpler version.
Removed parameter "Tag" as it was not used.
Renamed variables to prevent them to collide with user variables with the same names.
* Do scripts in the template validate required arguments and fail by returning a non-zero exit code when things go …
> Refactoring

- step-templates/windows-service-check-status.json
* Check if the Windows service is Running or Stopped.
If the Service isn't in selected status, the process fails
> add status check for windows service

- step-templates/save-octopus-output-variable-with-scoping.json
This is a variation of Save Octopus Output Variable that has options for setting the scope of the saved variable.
> Adding Save Output Variable with Scoping

- step-templates/clone-tenant.json
- step-templates/create-tenant.json
> Add templates for Create Tenant and Clone Tenant

- step-templates/azure-load-appsettings-from-file.json
> Step template to load app settings from the json file into Azure webapp;

- step-templates/epplus-register-dll-gac.json
changed the default value (was referencing to a local folder's name which I'd like to hide :-) )
> default value changed for RegisteringDllFolderPath

- step-templates/octopus-artifact-collect.json
> Add new step to collect Artifacts

- step-templates/ssis-deploy-ispac-from-referenced-package.json
> Adding SSIS template that is worker compatible

- .github/PULL_REQUEST_TEMPLATE.md
The wording is unclear whether it means the script parameters or the step's parameters
> Revised template parameter name checklist item

- step-templates/wait.json
> Made the wait verbose.(Countdown timer in place)

- step-templates/flyway-migrate-bash.json
- step-templates/flyway-migrate-referenced-package.json
> Enhancing templates to use package variables.

- step-templates/mysql-add-database-user-to-role.json
> updating version number

- step-templates/azure-function-deployment.json
> Adding TLS directive

- step-templates/letsencrypt-route-53.json
Change from email to GitHub user.
> Chore: Fix last modified on Route53 Let's Encrypt

- step-templates/redgate-create-database-release-worker-friendly.json
- step-templates/redgate-deploy-database-release-worker-friendly.json
> Octopus bob redgate warning

- step-templates/roundhouse-database-migration.json
> Fixed dropdown bug.

- step-templates/docker-install-windows.json
Added step template to install docker on windows.
> Added step template to install docker on windows

- step-templates/docker-install-linux.json
Added step template to install docker on linux
> Added step template to install docker on linux

- step-templates/slack-notify-deployment.json
Added `UseServerUri` parameter to decide which base url should be used.
- if **False** (default - no breaking change) then `Octopus.Web.BaseUrl` variable will be used
- if **True** then `Octopus.Web.ServerUri` variable will be used
> Added UseServerUri parameter

- step-templates/file-system-rclone.json
> Add File System - rclone template

- tools/StepTemplatePacker/scripts/ConvertTo-OctopusJson.ps1
Fixes _pack.ps1 to work with PS Core.
> Fixed _pack.ps1 to work with PS Core

- step-templates/k8s-hpa-external-metrics.json
- step-templates/k8s-hpa-object-metrics.json
- step-templates/k8s-hpa-pod-metrics.json
- step-templates/k8s-hpa-resource-metrics.json
> Add step to deploy Kubernetes Horizontal Pod Autoscaler

- step-templates/sql-fix-orphaned-user.json
---
Fixed copy paste error for description.
> Fixed description

- chocolatey-pin-package.json
> (feat) Add Chocolatey pin package step template

- step-templates/releasenoteshub-pull-trigger.json
This pull request is for the addition of a new parameter "IgnoreIfExists".
> Update to releasenoteshub-pull-trigger step to support IgnoreIfExists parameter

- step-templates/aspnetcore-set-environment-variable-iis.json
> This template sets environment variables in the IIS configuration "registry" and does not require a web.config file.

- step-templates/winsw-install.json
- step-templates/winsw.json
> WinSW - Install Step Template

- step-templates/chocolatey-manage-features.json
> (feat) Add step template to manage Chocolatey features

- step-templates/chocolatey-manage-config.json
> (feat) Add step template to manage Chocolatey config

- step-templates/save-octopus-output-variable-with-scoping.json
Updated to allow empty collections when scoping parameters are empty
> Updated script to allow empty collections

- step-templates/octopus-certificate-expiry-check.json
Add Octopus Check Certificate Expiry step template
> Add Octopus Check Certificate Expiry step template

- step-templates/apexsql-devops-toolkit-deploy.json
- step-templates/apexsql-devops-toolkit-sync-data.json
- step-templates/apexsql-devops-toolkit-sync.json
> Added ApexSQL DevOps toolkit step template v2020.05 with improved quality

- step-templates/redgate-deploy-from-package-worker-friendly.json
> Adding ability to trust certificate

- step-templates/sql-update-job.json
> DO-290: Add step template for updating ms sql jobs

- step-templates/sql-add-database-user-to-role.json
- step-templates/sql-create-database-user.json
`sql-add-database-user-to-role.json`:
These parameters define the user needed to apply the `ALTER ROLE [$createRoleName] ADD MEMBER [$createSqlLogin]` command defined in the script, but the help text suggests the user needs `permissions to create a database`, and `permissions to create SQL Logins`.
`sql-create-database-user.json`:
These parameters define the user needed to run the `CREATE USER [$createSqlLogin] FOR LOGIN [$createSqlLogin] WITH DEFAULT_SCHEMA=[dbo]` command defined in the script, but the help text suggests the user needs `permissions to create a database`, and `permissions to create SQL Logins`.
* Is the name of the template consistent with the …
> Improve the HelpText for 2 parameters in a couple of the SQL Library step templates

- step-templates/file-system-check-disk-space.json
> Step Template: File System - Check for available disk space

- step-templates/octopus-worker-healthcheck.json
> Adding worker health check step.

- step-templates/remove-server-from-azure-load-balancer.json
> Fix for Category

- step-templates/sql-deploy-dacpac-package-variable.json
> Adding note in description for minimum version requirement.

- step-templates/deploy-child-project.json
> Spinning the version number

- app/components/TemplateBody.jsx
- app/components/TemplateItem.jsx
- gulpfile.babel.js
- package-lock.json
- package.json
Update dependency react-syntax-highlighter
> Update dependency react-syntax-highlighter

- step-templates/send-sms-using-messagebird.json
> Added github username to messagebird template and incrememented version

- step-templates/liquibase-apply-changeset.json
> Added link for Liquibase Pro Trial

- step-templates/hashicorp-vault-jwt-login.json
Add a new step template to login to a HashiCorp Vault using a JSON Web Token (JWT).
> Add step to login to hashicorp vault using a JWT

- step-templates/liquibase-apply-changeset.json
- step-templates/liquibase-run-command.json
> Updating/adding Liquibase templates

- step-templates/opslevel-create-deploy-event-bash.json
- step-templates/opslevel-create-deploy-event-ps.json
Hey @BobJWalker  - Thanks for the help - hopefully this is what you meant.
> bugfix: opslevel deploy event needs deferred package reference

- step-templates/elmahio-notify-deployment.json
- step-templates/elmahio-upload-source-map.json
The author of the elmah.io step templates are elmah.io really. Could be another person within elmah.io publishing updates next time why I would prefer just to use the organization name if possible.
> Changed author of elmah.io step templates to elmahio

- package-lock.json
- package.json
Update browser-sync dev dependency
> Upgrade of browser-sync

- step-templates/sql-execute-script.json
Added support for capturing output received from each command (via the `SqlInfoMessageEventHandler`) to an Octopus output variable.
Also did some general tidying up of the PS Script.
> Add support for capturing output to variables

- step-templates/azure-web-app-restart.json
> Correcting a scripting Error.

- step-templates/mariadb-create-user.json
> Version bump to fix my great shame

- app/components/TemplateList.jsx
- app/content/styles/components/_header.scss
- app/content/styles/components/_templatelisting.scss
- app/content/styles/variables/_variables.scss
- package.json
Minor theme update for the library.
**Before**
**After**
> Minor theme update

- .octopus/deployment_process.ocl
- .octopus/deployment_settings.ocl
- .octopus/schema-version.ocl
- .octopus/schema_version.ocl
---
Updates the deploy process to use az powershell modules.
> Update deploy process

- step-templates/ssis-deploy-ispac-from-package-parameter.json
---
Updates the description of the template informing the user of the current state and pinned version.  A new template is planned without the reliance of the SqlServer PowerShell module.
> Updates description

- step-templates/slack-send-notification-using-block-kit.json
> Step Template: Slack - Send Notification using Block Kit

- step-templates/azure-create-containerapp-environment.json
- step-templates/azure-deploy-containerapp.json
---
Adding the general description and updated the Environment description.
> Updated overall describption and the Environemnt parameter description

- app/components/TemplateBody.jsx
- app/components/TemplateItem.jsx
To allow viewing of Apply Terraform step source
Heres what the view looks like before the change
Collapsed:
Expanded:
> Add support for terraform apply steps to be viewed

- step-templates/deploy-child-project.json
No-op change to get build to run for previous PR #1434
> No-op change to get build to run

- .github/pull_request_template.md
This PR updates the PR template to link to the best practices wiki page.
> Added a link to the wiki

- .octopus/deployment_process.ocl
---
Worker pool update for library deploy
> Update worker pool

- .github/workflows/Hyponome.yml
Adds a link to hyponome for easier reviewing.
See below.
> Hyponome link

- step-templates/github-verify-attestation.json
- Bug fix for Verify GitHub Attestation step
> Remove feedid from Verify GitHub Attestation step
