step-templates/edgecast-cdn-purge.json
If anyone, like me, you want to purge the EdgeCast CDN cachen after deploying via Octopus this step template can be used.
It requires a user account with EdgeCast, an API token and the URI to be purged.
=> Added new step template to purge EdgeCast CDN cache after deployment

step-templates/TeamCity-Pin-Build.json, step-templates/windows-service-stop-or-kill.json
This pull request includes 2 step template.
1. Windows Service with kill will try to stop a service, if this does not work, the service will be killed
2. Pin TeamCity Build will try to PIN the build in TeamCity, e. g. on GoLive day make sure TC will not remove packages.
=> 2 Steps: Windows Service With Kill + Pin TeamCity Build

app/areas/listing/search_criteria.js
I guess somebody sneaked in a step template without a description and broke the search :smile: This works around the problem and possibly fixes it (depends on whether a step template without a description is allowed).
=> checking agaisnt null for description during search

app/areas/listing/listing.js, app/areas/listing/listing_index.js, app/areas/listing/search_criteria.js
With these changes, you can now get a link for a search. For example, if you hit *localhost:4000/#!/listing/redgate*, it will search for **redgate** on the page landing:
Note:
- I wasn't able to find a way to reflect the search input value changes to URL. Would be nice to add that as well.
- If this makes it in, we will use a link to direct users to our step templates. So, it's important not to break this `/#!/listing/:searchTerm?` route pattern if possible :smile:
=> added link support for search

step-templates/teamcity-trigger-build.json
This pull request contains a step template for triggering Team City builds. This can be useful for example when you want to run API tests from Team City on services deployed with Octopus Deploy.
=> Added a step template for triggering Team City builds.

step-templates/aws-execute-powershell.json, step-templates/execute-aws-powershell.json
This pull request contains a new template for executing commands against AWS via the AWSPowershell module. I was previously accomplishing this same work by creating three different steps in a deployment, which seemed like a bit much, so I decided to simplify it down to just one step that it really needed to be.
The template was created by combining the work of [this template](http://library.octopusdeploy.com/#!/step-template/actiontemplate-chocolatey-ensure-installed) that checked for Chocolatey being installed and [this template](http://library.octopusdeploy.com/#!/step-template/actiontemplate-chocolatey-install-package) that installed a package via Chocolatey to install the AWS Powershell tools, and then added on my own piece of having it import the AWSPowershell module and then …
=> adding execute aws powershell template step

step-templates/sql-smo-create-database.json, step-templates/sql-smo-drop-database.json
Redgate doesn't yet offer support for creating a database. These come in handy when ripping down and rebuilding databases in an unstable CI environment.
=> Steps to Drop and Create a database using Sql Server Management Objects

step-templates/ssl-certificate-install.json
I find the key set flags in this template to be a bit subpar. I had to add "MachineKeySet" to the flags in order to have the private key imported. Furthermore, I doubt that you would need to ever export the private key from one of the production machines, so I would vote for removing "Exportable". In sum, I would suggest the key storage flags to be "MachineKeySet,PersistKeySet" instead of "Exportable,PersistKeySet"
=> Change key storage flags to MachineKeySet,PersistKeySet

step-templates/windows-service-restart.json
I had a problem when on of my tentacles was installed on a machine running powershell 2.0. After adding `-InputObject` to the powershell script, it worked. It also worked with tentacles that were running ps 4
=> fixed restart-service so works with powershell 2.0

step-templates/iis-apppool-stop.json
Added a counter with timed delay to wait for the Application Pool to completely shut down (State "Stopped") before proceeding.
=> Check if app pool is stopped before proceeding

step-templates/file-system-create-folders.json
fixed issue with trailing ; causing the script to try to create a folder for an empty string.  The script will now fail by default if it cannot create a folder with the option to allow the script to continue with failures with a log.
=> fixed issue when there is a ; trailing folder names

step-templates/windows-add-back-connection-host-name.json
Step template for adding back connection host names to Windows registry. Disables loopback checking for a given host header name, allowing an IIS site running with integrated authentication to be accessed from the same machine. Common for web to API connections. See <https://support.microsoft.com/en-us/kb/896861> for more information.
=> Step template for adding back connection host names to Windows registry

step-templates/windows-ensure-hosts-file-entry-exists.json
Step template to ensure that the given IP/host name entry exists in the Windows hosts file. Step is idempotent and can be run several times without adding duplicate entries.
=> Step template to ensure Windows hosts file entry exists

step-templates/configuration-encrypt-section.json
This fixes a problem where when you encrypt a section in your config files, files that are referenced are not encrypted. For example, if my Web.config file contains this:
```
<config>
...
<connectionStrings configSource="ConnectionStrings.config" />
...
</config>
```
And my "section to encyrpt" is `connectionStrings`, I want the content in `ConnectionStrings.config` to be encrypted.
After this change, you can specify a list of files to be included (along with the main file (e.g. web.config)) to be searched for the proper config section to encrypt.
=> Encyrpt section works with external connectionString.config files

step-templates/iis-website-add-release-number-to-response-header.json
Using Octopus parameter "Octopus.Step.Package.NuGetPackageVersion" resulted in an empty release number, because the parameter should be used as "Octopus.Step[step_name_here].Package.NuGetPackageVersion".
Replaced Octopus parameter "Octopus.Step.Package.NuGetPackageVersion" with "Octopus.Release.Number" to solve this.
=> Doesn't seem to work with "Octopus.Step.Package.NuGetPackageVersion" parameter

step-templates/iis-app-update-property.json, step-templates/iis-apppool-update-property.json, step-templates/iis-autostartprovider-add.json, step-templates/iis-website-update-property.json
Hi Guys
Those are step templates I used to configure my IIS website to hot start using autostartenabled, serviceautostartprovider and apppool start mode. This is example:
IIS AppPool - Update Property - Start Mode -AlwaysRunning
* propertyName: startMode, propertyValue: AlwaysRunning
IIS WebSite - Update Property - AutoStartEnabled - True
* propertyName: applicationDefaults.serviceAutoStartEnabled, propertyValue: True
IIS WebSite - Update Property - ServiceAutostartProvider
* propertyName: applicationDefaults.serviceAutoStartProvider, propertyValue: ProviderNae
But those templates can be used to set most of the properties of AppPool, WebSite, Application.
=> Update property step templates for AppPool, WebSite, App

step-templates/file-system-regular-expression-find-and-replace.json
Originally the script didn't handle any $ syntax - as if it was deleting
them even if multiples were used to quote.  This change re-enables the $
syntax for replacements allowing grouping to be used in the replacement
string.  And $$ quotes a single $ into the output too.
=> Now $ replacement syntax works

step-templates/windows-wait-for-or-force-close-application.json
Created script that will wait a set time for a process to close and optionally force kill the process.
=> Wait a set time for a process to close and optionally force kill the process.

step-templates/windows-create-shortcut.json
* Fixed a bug where the script used $shortcutPath instead of $OctopusParameters['shortcutPath']
* Introduced predefined folders for shortut destinations starting with Public Desktop. 
The script is backward compatible if Custom is set as Shortcut destication.
=> Improved Windows - Create Shortcut step template

step-templates/seq-log-deployment.json
Hello!
This template allows the result of a deployment - success or failure - to be logged to a [Seq](https://getseq.net) log server.
This makes it possible to quickly correlate deployment events with other things going on in an environment - events/errors/etc.
=> Added the "Seq - Log Deployment" step template

step-templates/msmq-create-transactional-queue.json
The 'Domain Admins' user account was hard coded into the script and the 'Domain admin permissions' was relying on that user to be listed for the permissions to be added. This was pretty opaque.
This update makes who is an admin and what permissions they have totally configurable. Also, fixes the execution failure if the allow or deny was empty.
=> Added better support for Admins

step-templates/file-system-clean-configuration-transforms.json
We had a project where config files were being incorrectly deleted e.g.
'Sitecore.Analytics.config' in the original implementation. Now you can
target specific names for the powershell filter so the regex becomes
*.VARIABLE.config. Variable can be e.g: * (default), #{Octopus.Environment.Name}, Release or
anything you want.
=> Update config transform cleaner to allow name parameter

step-templates/configuration-encrypt-web-config-section.json
Updated the Web.config encrypt step template to support multiple sections.
Added `-split ',' | where {$_} | %{$_.Trim()}` for the **SectionsToEncrypt** parameter.
=> Add multiple section support when encrypting config files

step-templates/clickonce-sign-file.json, step-templates/clickonce-update-application-file.json, step-templates/clickonce-update-manifest-file.json
Contains three scripts which are useful if you want to manipulate clickonce manifest and application files during a deployment. There is an exsisting ClickOnceRe-Sign template but it has some hardcoded path and tightly couples all individual steps. I created separate steps for each action and add extra parameters to be more flexible.
=> ClickOnce related step templates

step-templates/sql-deploy-dacpac.json
Can now generate deployment reports and deployment scripts which are loaded back into Octopus Deploy as artefacts.  This gives the option of creating a multi step process with manual intervention in the middle.
Dropped support of VS version of SSDT.  The script now searches %Program Files% looking for the most recent version of DacFX deployed on the server.
This is quite a substantial set of changes from the previous version and may warrant its own template within the library.  If that is preferred I will create a separate PR for that - just let me know.
=> Add support for other DacFX commands

step-templates/octopus-chain-deployment.json
Step template that will trigger a deployment for a different project in Octopus, allowing chained deployments in the case of dependencies between projects.
Release creation options include creating a release if one doesn't already exist (default), always creating a release, and never creating a release.
By default, the chained Deployment will have the same version number as the Release being deployed, and the project will be deployed to the same environment as the current deployment. These can be customized.
This step template is relatively basic and does not allow for specifying package versions or prompted variables for the target project.
=> Add Chained Deployment step template

step-templates/teamcity-pin-build-and-dependencies.json
This template uses the AJAX endpoint of the UI instead of the REST API one to allow pinning and tagging the build dependencies
=> Added step template to pin TeamCity build and dependencies

step-templates/iis-website-update-property.json
Previous version was failing with properties like applicationPool with below error :
System.Management.Automation.PSArgumentException: Property "Value" cannot be found.
The following shows different combinations handled by this change :
(Get-ItemProperty "IIS:\Sites\Default Web Site" -Name "ApplicationPool").GetType().Name
PSCustomObject
(Get-ItemProperty "IIS:\Sites\Default Web Site" -Name "applicationPool").GetType().Name
String
(Get-ItemProperty "IIS:\Sites\Default Web Site" -Name "logFile.directory").GetType().Name
ConfigurationAttribute
Example test cases with properties name/value pairs:
- applicationPool : pool1
- logFile.directory : C:\Temp
- traceFailedRequestsLoggin.enabled : True
=> Allow passing property names with any character case and also handle different types of web site properties in a better way

step-templates/sitecore-settings-variable-replacement.json
This step template iterates over the $OctopusParameters collection and replaces matching keys in the specified Sitecore configuration file(s). This is intended to extend the functionality of [Configuration Variables](http://docs.octopusdeploy.com/display/OD/Configuration+files#Configurationfiles-ConfigurationVariables) to the Sitecore configuration files.
Sitecore is a content and experience management system that requires a purchased license to operate, however, the functionality of this step template does not rely on it - it simply replaces values in XML files under a specific node structure that matches the Sitecore config files.
=> Adding step template to replace Sitecore configuration settings

step-templates/iis-set-authentication.steptemplate.json
Hi Team,
We (asos.com) are contributing our first step template towards the community library. 
We are legally covered with the Apache 2.0 License.
This template is for enabling or disabling the authentication methods for the IIS site(s). This template will configure the desired state of authentication for the IIS site(s).
We have verified that the existing template for Windows Authentication providers serves a completely different purpose to ours.
Let us know if you are happy to merge?
Thanks & Regards,
Benitha (ASOS.com)
=> Step template for setting IIS Authentication methods

step-templates/iis-set-authentication.steptemplate.json
Previously the list of valid IIS sets only included websites. This change also identifies all the applications within that website as valid paths.
=> IIS Set Authentication on IIS Applications

gulpfile.babel.js, package.json, spec/step-template-validation-tests.js, step-templates/readyroll-deploy-database-package.json, step-templates/redgate-create-database-release.json, step-templates/redgate-deploy-from-database-release.json, step-templates/redgate-deploy-from-database.json, step-templates/redgate-deploy-from-package.json
As LastModifiedOn/LastModifiedBy details are no longer exported, this
causes issues when we display on the community library.
This will/should cause a build failure.
Related to #354.
=> Add test for missing last modified details

step-templates/file-system-grant-permissions.json
Fix bug with setting owner by not using Get-Acl. See http://stackoverflow.com/questions/6622124/why-does-set-acl-on-the-drive-root-try-to-set-ownership-of-the-object
Better logging
Better variable names
=> Improve file system grant permission

step-templates/retention-policy.json
Applies retention policy for built-in package repository by specified package id. Useful when you are using variables in PackageId parameter of deploy package step and built-in retention policy for package repository is not deleting packages.
=> Added Retention Policy script.

step-templates/file-system-backup-directory.json
Changed variable names to something less generic ti avoid clashes with
project/library variables
"Source" => "BackupSource"
"Destination" => "BackupDestination"
Ticket: https://secure.helpscout.net/conversation/240474620/9153 (and
this has happened at least 1 more time with this template)
=> Changing variable names to something less generic

step-templates/windows-ensure-features-installed.json
[windows-ensure-features-installed] Some features may not be enabled if their parent feature is not enabled as well. Use /All option to enable all parent features if necessary.
=> add /all option to fix parent not selected bug

step-templates/Wait-until-time
This step template will pause the octopus process until a given time.
Intended use:
Any time when the process needs to be halted. For example when using a Manual Intervention step to approve the deploy but the user wants the deploy process to continue automatically at night.
Description
It has 2 parameters: DefaultTargetTime that is a step parameter and TargetTime that is a release variable.
If no configuration is given (DefaultTargetTime and TargetTime is not set) the step will continue emmidiately.
If the step parameter DefaultTargetTime is set but not TargetTime, the step will wait until DefaultTargetTime
If TargetTime is set in the release variables for the environment that the release is targeting the step will wait until TargetTime. 
It is possible to make TargetTime as a promptable …
=> New step template Wait-until-time

step-templates/hg-get-changelog.json
Creates a changelog (based on Mercurial source control commit messages) as HTML fragment which can be used for instance in a mail notification after a successful deployment.
The script is made so that it takes into account the currently deployed version on the target environment, thus producing a log of changes since the last deployment.
=> Step template for generating a changelog from Mercurial commit messages

step-templates/run-entity-framework-migrations.json
**Run Entity Framework migrations (Update-Database)** currently has a problem described in [my comments to this library](https://library.octopusdeploy.com/step-template/actiontemplate-run-entity-framework-migrations-(update-database))
Long story short. This library should follow [the official EF migration guide](https://msdn.microsoft.com/en-us/data/jj618307.aspx?f=255&MSPPError=-2147217396) that **Once you have migrate.exe then you need to copy it to the location of the assembly that contains your migrations.**
Right now, this library generates a command looks like this:
& "C:\TeamCity\buildAgent\work\43efbaad108eb32f\packages\EntityFramework.6.1.3\tools\migrate.exe" "FHT.Infrastructure.MsSqlConfigurations.dll" /connectionString="" /connectionProviderName="System.Data.SqlClient" …
=> Copy migrate.exe to ASP.NET project's bin folder and also replace connectionString by connectionStringName

step-templates/ssl-certificate-install.json
The StoreName string of intermediate certificate authorities should be "CA", not "CertificateAuthority".
=> Fix StoreName select options error.

step-templates/sql-execute-script-with-authentication.json
Execute a SQL script using SMO using either SQL or windows authentication,
Option also exists to specify a previous step if SQL scripts extracted/created in previous step.
=> add sql execute script with authentication

step-templates/statuspageio-create-scheduled-maintenance-incident.json, step-templates/statuspageio-update-scheduled-maintenance-incident.json
Introduces two new templates for Atlassian's StatusPage.io. One template is for the creation of a new scheduled maintenance incident. The other template allows one to update an existing scheduled maintenance incident by name.
=> Adds StatusPage.io Incident Creation Templates

step-templates/windows-scheduled-task-create.json
The powershell script expects variable name "RunAsPassword", but Octopus variable name is "Password".
=> Fixed wrong parameter name

step-templates/upgrade-octopus-server.json
This step downloads the latest version of Octopus Server and upgrades an existing instance. Run this step on a tentacle that has privileges to install software and start/stop services on the target server.
**Run this after a database backup step**
To Use:
- Install a tentacle on the Octopus Server machine with privileges to install software and start/stop services
- Add that tentacle to an environment and with a unique role
- Setup a project for the upgrade process
- Add a database backup step for your Octopus Server database
- Add this step, selecting it to run on just the role previously configured
- Create a release
- Deploy that release whenever an upgrade is needed
NB: The deployment will show as "Timed Out" when the server comes back online
=> Added Upgrade Octopus Server Step

step-templates/configuration-encrypt-app-or-web-config-section.json
Added the step template to encrypt the app.config or web.config based on the parameter selected.
This is not dependent on the regiis.exe to encrypt the web.config. Works well when the encrypting multiple sections like appSettings and connectionStrings.
=> Configuration to encrypt both app or web config from a step template

step-templates/msmq-create-transactional-queue.json
_Remove additional permission which may have been added to the Queue without deleting any of the existing messages._
- A new checkbox has been added which will remove existing permissions for a Queue if it already exists
- Only users which belong to the specified domain will have their permissions removed
Deleting and re-creating the Queue may result in you loosing messages.
=> optional permissions reset for transaction queue

step-templates/F5-API-enable-disable-member.json
This step-template allows users to work with F5 API.
With this feature, it is possible to run the same process from multiple servers without iControl snap-in installed.
=> F5 - work with API

step-templates/windows-scheduled-task-disable.json
The script now explicitly checks if the PowerShell cmdlts for handling scheduled tasks are available. Furthermore, the script now checks for the state of a scheduled task in a language independent way
=> The script now explicitly checks if the PowerShell cmdlts for handling scheduled tasks are available

step-templates/aws-cloudformation-create.json
Removes current limitations that don't allow users to have bars or colons in parameters. Json blob can just be added as a parameter instead. Also makes the deletion of stacks with the same name optional (will use -Force if option is selected, which means no powershell intervention is required).
I'll paste in the bits of the script I've changed since it's a bit hard to read in the diff.
The CloudFormation parameter parsing now looks like this:
```ps1
#Reformat the CloudFormation parameters
$paramObject = ConvertFrom-Json $CloudFormationParameters
$cloudFormationParams = @()
$paramObject.psobject.properties | ForEach-Object { 
$keyPair = New-Object -Type Amazon.CloudFormation.Model.Parameter
$keyPair.ParameterKey = $_.Name
$keyPair.ParameterValue = $_.Value
$cloudFormationParams += $keyPair …
```
=> Modify to take json params for cloudformation

step-templates/elmahio-notify-deployment.json
We've recently switched from prefixing every deployment, to allowing specifying which log we want the deployment belonging to. This makes the prefix variable unnecessary. An optional property for specifying the log ID has been added.
=> Corrections to support a new API

step-templates/iis-website-stop.json
I had the problem that the Website wasn't stopped completely before the next step. So i followed the example of https://library.octopus.com/step-templates/3aaf34a5-90eb-4ea1-95db-15ec93c1e54d/actiontemplate-iis-apppool-stop to apply the same technique for waiting until the Website is stopped before completing the step.
=> Make "IIS Website - Stop" synchronous like "IIS AppPool - Stop"

step-templates/slack-notify-deployment.json
-  Add links back to project and release on Octopus Deploy server
-  Include target roles in message
-  Check if target machine is blank (e.g. if step targets all roles and is running on deployment server)
=> Add links in slack message back to Octopus server

step-templates/octopus-consolidate-releasenotes.json
Looks at the previous deployment in an Environment and concatenates all release notes in Releases since that date, then updates the current Release's release notes
Note that this doesn't page, so there's an implicit limit to the last 30 releases.
=> Release Note consolidation step

step-templates/sql-execute-script.json
- Default value of ContiunueOnError being blank was causing an issue at runtime where the value was being detected as Null, causing the script to fail.
- Updated $ContinueOnError variable in the PS script to be more consistent with the other octopus variable formats used in the script.
- Updated version to 4.
- Updated LastModifiedOn/By.
=> Updated script and ContinueOnError default value.

step-templates/slack-detailed-notification.json
Added new step template. It posts deployment status to Slack optionally including additional details (release number, environment name, release notes etc.) as well as error description and link to failure log page.
The work is base on existing "Slack - Notify deployment" step template, however is significantly different to merge with the existing one and probably cause issues for existing users.
=> Added new step template 'Slack - Detailed Notification'

step-templates/sql-smo-change-usermode.json
Use SMO to set [UserAccess](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.database.useraccess.aspx) property for a database.
The 3 available [options](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.databaseuseraccess.aspx): Multiple, Single and Restricted are represented as a drop down option.
Can take optional uname/pword for SQL user or will fallback to integrated authentication (same as other SMO templates).
=> Added new step template to set user access mode with SMO

step-templates/sql-smo-drop-database.json
I ran into an issue with the "SQL - Drop Database Using SMO" task as `$null` was passed into step but the check for optional username and password parameters was `if ($SqlUsername -eq "" -and $SqlPassword -eq "")`.
Updated check to be `if (!$SqlUsername -and !$SqlPassword)` to handle null and empty string.
Originally discussed in an [issue](http://help.octopusdeploy.com/discussions/problems/53063-optional-parameters-are-null-rather-than) on forum.
=> Handle optional parameters in drop-database-smo task

step-templates/network-add-url-reservation.json
Task was failing with error _parameter incorrect_ when trying to assign urlacl reservation for user "NT Authority\Local Service".
Resolved issue by updating script to wrap `username` parameter in quotes so it becomes:
`http add urlacl url=http://+:8888/ user="NT Authority\Local Service" -delegate=no` 
rather than
`http add urlacl url=http://+:8888/ user=NT Authority\Local Service -delegate=no`
=> Update url reservation template for handling username with spaces

step-templates/iis-apppool-stop.json
Include simple output message when an IIS app pool is already stopped.
=> IIS AppPool Stop: log a notification when an app pool is already stopped.

step-templates/rollbar-notify-deployment.json
Added a new parameter `RevisionFilename` that can be assigned the filename (or full path) of a file that contains the version (e.g. full _git-sha_). This can be a practical way of obtaining the version, after writing it to a file during the build process and then deploying it.
If `RevisionFilename` is assigned a value, the `Revision` parameter is ignored.
=> Rollbar notify deployment support for reading version from file

step-templates/file-system-create-file.json
Fixes #519.
Adds an `Encoding` dropdown with the valid values for the `Set-Content` cmdlet.
=> Add encoding to File System - Create File

step-templates/http-test-url.json
The HTTP - Test Url Step Template has a bug when using it with authentication. The Username and Password Parameters are misnamed
=> Fix for misnamed parameters in HTTP - Test Url Step Template

step-templates/sql-smo-create-login-and-user.json
We have many apps where we prefer to assign a few different roles (e.g. db_datareader and db_datawriter) so I propose an update which allows multiple roles if comma separated. Also I've uncommented the Exit 1 statement in the catch block, the script should fail the deployment in my opinion if it can't create the user or login otherwise you end up with a successful deployment which didn't actually succeed in one of the key steps.
---
=> Allow assigning multiple roles to a user and fail the script on exception

step-templates/letsencrypt-create-ssl-certificate.json
Procures an X.509 SSL Certificate from the [Let’s Encrypt](https://letsencrypt.org) Certificate Authority using the [Automatic Certificate Management Environment (ACME)](https://ietf-wg-acme.github.io/acme/) protocol.
=> Lets Encrypt - Create SSL Certificate

step-templates/aws-add-remove-elbv2.json
This step template allows you to add or remove the current machine from a [Target Group](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html) associated with the newer type of ELB ([Application Load Balancer or ELBv2](https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/)).
=> Add template to add/remove AWS instances from the newer type of ELB

step-templates/dsc-windows-service.json
--- Efficiently align Windows services to a desired state (stopped/started)
=> Added DSC Windows Service template

step-templates/elmahio-notify-deployment.json
Wrap call to rest api in try catch, since creating deployments can fail. This usually happen if user inputted the wrong api key or when running the same process on multiple deployment targets (results in 409 from the api)
=> Wrap rest call in try catch to allow allow deployment even though call to elmah.io fails

step-templates/Azure-Get-Publishing-Credentials.json
A step template for obtaining the publishing credentials used for a Web App in a resource group.
I'm planning on using this in conjunction with the community step template for deploying Azure Functions... at least until Octopus Deploy's 'Deploy Azure Web App' step supports this natively.
One potential issue... this step template sets output variables for the username and password; will the password appear in Octopus Deploy logs? `Set-OctopusVariable` doesn't appear to support a way to indicate that the variable is sensitive.
=> Get Azure Web App Publishing Credentials

step-templates/windows-ensure-features-installed.json
=> Consider all DSIM states that begin with "Disabled" to be disabled

step-templates/file-system-grant-permissions.json
=> Update file-system-grant-permissions.json - Added folder path output

step-templates/topshelf-uninstall.json
=> User Start-process instead of &

step-templates/windows-scheduled-task-disable.json
When a task wasn't found the step was succeeding in Octopus. An error should be raised if the task wasn't found.
This could potentially break deployments that were relying on this behavior. So I also added a toggle to prevent the error and maintain backwards compatibility
---
=> Change task not found behavior to throw error

step-templates/topshelf-install.json, step-templates/topshelf-uninstall.json
Topshelf scripts by default uses ["Octopus.Action[$step].Package.NuGetPackageId"] + ".exe" as a service name, but conventions for naming exe and package ids usually different.
The new parameter is introduced for customizing exe file name. If the parameter value is empty, then the old behavior is used.
=> Add optional custom exe filename parameter for topshelf 

step-templates/slack-detailed-notification.json, step-templates/slack-notify-deployment.json
=> Tls1.2 Support for Slack Detailed Notification and Slack Notify Deployment templates

step-templates/upgrade-octopus-server.json
Comment: Added the parameter SpecificVersionInstallation to the template. Dunno if it's a good name or not. But the parameter has comments which outlines its purpose.
=> Added the possibility to set specific version of Octopus Server to install

step-templates/azure-remove-resource-group-deployments.json
=> Adds octopus step template - "Azure - Remove Resource Group Deployments"

step-templates/bash-check-net-core-framework-version.json, step-templates/windows-check-net-core-framework-version.json, step-templates/windows-check-net-framework-version.json
For .NET Core templates powershell and bash versions are provided.
=> Add step templates for .NET and .NET Core runtime version check

step-templates/windows-service-set-recovery-on-failure-actions.json
Fix for typo in `$thirdFailureDelay` variable name.
Use `""` instead of empty string for "Take no action" to avoid it being replaced with the default `restart`.
---
=> Fixes for "Windows Service - Set Recovery on Failure Actions" step template

step-templates/amazon-s3-upload.json
This update adds a new parameter to the S3 Upload function allowing a user to add a Prefix.
I needed this so we could version off our assets into S3 by prefixing with the deployment environment and version.
i.e
`#{Environment}/#{Octopus.Release.Number}/`
Then all the files from the source will be in the sub-directory of:
`/staging/8.232.0/`
----
=> Added parameter to support uploading files with s3 prefix 

step-templates/microsoft-teams-post-a-message.json
This PR only changes the `-ContentType` powershell parameter to include the encoding.
Without it, the inferred encoding by the webhook is ANSI, which does not work.
I have tested the fix manually by sending requests using powershell directly:
```powershell
$payload = @{ title = 'Test'
text = 'Message avec accents : éèû'
}
Invoke-RestMethod -Method POST -Uri https://outlook.office365.com/webhook/xxx/IncomingWebhook/xxx -Body ($payload | ConvertTo-Json -Depth 4) -ContentType 'application/json; charset=utf-8'
```
=> Fix missing encoding when posting to MS Teams webhook

step-templates/slack-send-simple-notification.json
Makes the 'Message' field for Slack notifications into a multiline text area.
=> Make Slack notification message field MultiLineText

step-templates/azure-add-service-fabric-cluster-certificate.json
=> Add service fabric cluster certificate

step-templates/windows-service-change-binary-path.json
- [x ] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
- [x ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [x ] Parameter names should not start with `$`
=> New step: Windows service - Change binary path

step-templates/ftp-uploadfiles.json
Extend the ftp-uploadfiles step template to support SFTP deployments via the Host Key Fingerprint parameter, as well as enable the use of Private Keys to authenticate with the server - these need to be deployed to the tentacle first, until such time as the SSH Account is made available to powershell.
=> Updated ftp-uploadfiles to support SFTP deployments.

step-templates/redgate-create-database-release.json, step-templates/redgate-deploy-from-database-release.json, step-templates/redgate-deploy-from-database.json, step-templates/redgate-deploy-from-package.json
This PR updates the Redgate SQL Change Automation step templates for the 2018-07-10 release.
=> Update Redgate SQL Change Automation for 2018-07-10 release

step-templates/redgate-create-database-release.json, step-templates/redgate-deploy-from-database-release.json, step-templates/redgate-deploy-from-database.json, step-templates/redgate-deploy-from-package.json
I found an issue in the powershell scripts (if there is something obvious I'm missing, please let me know!)
The parameter SpecificModuleVersion has a default value of null, but it is passing an empty string to the script. The script is then calling a function (InstallCorrectSqlChangeAutomation) that is trying to cast it to a Version type. If it's empty, it crashes with:
>  Cannot process argument transformation on parameter 'requiredVersion'. Cannot convert value "" to type "System.Version". Error: "Version string portion was too short or too long.
I simply added a check for this and set it to null instead.
`if ($SpecificModuleVersion -eq '') {
$SpecificModuleVersion = $null
}`
Updated versions, last modified, and timestamp.
=> RedGate - Empty version crash

step-templates/redgate-create-database-release.json, step-templates/redgate-deploy-from-database-release.json, step-templates/redgate-deploy-from-database.json, step-templates/redgate-deploy-from-package.json
Updates step templates for SQL Change Automation to improve handling of optional parameters.
- ~If a new `Category` has been created:~
- ~An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder~
- ~The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it~
=> Update SQL Change Automation step templates

step-templates/save-octopus-output-variable.json
The main change is updating the output of the existing variable value to
`Write-Verbose "Existing value: $(if ($_.Type -eq 'Sensitive') { "********" } else { $_.Value })"`
This way if the existing variable is sensitive, it won't write the value to the log.
It looks like VS Code updated the whitespace / formatting on the file.
=> Updated to mask existing value if it is sensitive

package.json
To fix security alert:
GHSA-mh6f-8j2x-4483 - critical severity
Vulnerable versions: > 3.3.4
Patched version: No fix
The NPM package flatmap-stream is considered malicious. A malicious actor added this package as a dependency to the NPM event-stream package in versions 3.3.6 and later. Users of event-stream are encouraged to downgrade to the last non-malicious version, 3.3.4.
Note: there was no vulnerable code referenced - this just prevents an issue if we run `npm update`.
=> Lock event-stream to 3.3.4

step-templates/iis-app-update-property.json
I've left the parameter as it was, because this is an upgrade, if we want this we can do another version with this breaking change
=> [iis-app-update-property] Changed how the item property is read

step-templates/json-merge.json
=> Updated json merge step template to fix issue where some symbols from json files where read incorrectly

step-templates/aws-add-imagetag-to-all-used-ecr-packages.json
=> Added template for tagging ECR images with deployment imagetags

step-templates/slack-send-simple-notification.json
=> Make sure we link mentions properly in message. Fixes #762

step-templates/iis-website-add-release-number-to-response-header.json
```
Exception calling "GetSection" with "2" argument(s): "Filename: redirection.config
Error: Cannot read configuration file
```
Credit for revealing the root cause (in some instances the script would load the incorrect assembly, which in turn would try to modify the incorrect configuration file):
https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/191#issuecomment-238687014
Credit for the solution:
https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/462
Note that this may cause Octopus to prompt users who update the step in existing processes to do so manually.
---
=> iis-website-add-release-number-to-response-header: Fix error

step-templates/github-report-deployment.json
The `github-report-deployment` step template had default values specified like
```
"DefaultValue": {	      "DefaultValue": null,
"HasValue": true,	
"NewValue": null	
},
```
where they should just be
```
"DefaultValue": null,
```
This broke the parsing inside octopus
=> Github - report deployment had invalid parameters

step-templates/elmahio-notify-deployment.json
I've modified the notify deployment script for elmah.io to use TLS 1, 1.1 or 1.2 only.
=> Support for TLS 1, 1.1 and 1.2 only

step-templates/sql-create-database.json
I got a timeout error when trying to create a database in Azure.  Added timeout parameter with the standard default value.
=> Updated create sql database step

step-templates/ssis-deploy-ispac-from-referenced-package.json
---
Fixes issue where feed for referenced package was hardcoded to the Default feed id.  It's now a variable that can be changed.
=> Fixed hardcoded value of Spaces-1 builtin feed

step-templates/datadog-create-event.json, step-templates/datadog-schedule-downtime.json
=> made datadog steps use basic parsing so they work with octopus cloud

README.md, step-templates/gitlab-create-tag.json
When step templates are exported from Octopus Deploy, if the parameter is sensitive it will be exported as an object, which causes issues with syncing. We will look into better validation for this. For now I've updated the readme to remind us to check that parameter `DefaultValue`s are either a string or null, and not an object.
This PR also updates the `gitlab-create-tag.json` file to fix the same issue.
=> Update readme. Fix sync issue caused by invalid json.

step-templates/run-pulumi-on-linux.json, step-templates/run-pulumi-on-windows.json
In a previous PR I contributed the Step Template for Pulumi that can be used with Linux-based Workers. This adds the Windows version, which utilizes PowerShell.
=> Add Pulumi Step Template to be used for Windows workers

step-templates/windows-scheduled-task-changepath.json
The "Windows Scheduled Task - Change Path" step template has logic to behave differently on Server 2012 vs. Server 2008. I found a couple of issues in the 2012 logic.
First, the username is enclosed in quotes when passed as an argument to the command, which was needed for the 2008 command, but fails with the 2012 command. I have made this behavior specific to 2008.
Secondly, the PowerShell command to define the action for the scheduled task was incorrect. The script was attempting to use the `-TaskPath` argument in `Set-ScheduledTask` to set the path of the executable - however, [that is not the purpose of `TaskPath`](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/set-scheduledtask?view=winserver2012r2-ps). Instead, an action needs to be created with …
=> Fix scheduled-task-changepath for Server 2012

step-templates/flyway-migrate-referenced-package.json
This version will allow the step to be executed from a worker by use of a referenced package.
---
=> Adding new template for flyway 

step-templates/flyway-migrate-bash.json
---
- [X ] Parameter names should not start with `$`
- [X ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
=> Adding Bash version of Flyway Migrate

step-templates/flyway-migrate-referenced-package.json
=> Fixing Flyway migrate from a referenced package name

step-templates/linux-service-start-stop-restart.json
=> Adding template to start, stop, or restart linux service

step-templates/run-octopus-runbook.json
=> Added a step to run a runbook from another runbook or deployment process

step-templates/slack-send-simple-notification.json
Fixes #863 If there is an open issue that this PR fixes add it here, otherwise just remove this line_
Changes:
- remove `parse="\full\"`
- add `link_names = \"true\"`
Re [link_names](https://api.slack.com/methods/chat.postMessage#arg_link_names) docs
=> Use slack formatting while resolving mentions. Fixes #863

step-templates/flyway-info-bash.json, step-templates/flyway-info.json
=> Adding flyway info templates.

step-templates/http-test-url.json
=> Force TLS 1.2 for http test url step template

step-templates/letsencrypt-route-53.json
The follow line in Route53 step template parameters breaks E2E Tests in 2020.1 release stream. 
```
"DefaultValue": {
"HasValue": true,	
"NewValue": null	
}
```
=> Bug: Exported default value breaks sync.

.gitignore, step-templates/octopus-import-certificate.json
Added a parameter to provide the Octopus Server URL. It is defaulted to Octopus.Web.BaseUrl to match current functionality. Cloud instances need to use Octopus.Web.ServerUri.
Also added the TLS logic needed by cloud instances to make requests to the API.
=> Updated Import Certificate to work with cloud instances

step-templates/sitecore-deploy-scwdp.json
=> Sitecore web deploy package (.scwdp) deployment

step-templates/file-system-rsync.json
=> Add File System - rsync template

step-templates/ssis-deploy-ispac-from-package-parameter.json
---
Fixes issue where feed-id doesn't work in existing package.
=> Adding new template to maintain backwards compatibility with existing

step-templates/run-mabl-tests.json
Changes:
* Fixed an issue with executing test plans with labels
* Added an option to specify mabl test branch name
* Updated the output to include URL reference to deployment
* Updated the output to provide additional details on test runs
=> Minor changes and improvements to the Run mabl tests step template

step-templates/letsencrypt-create-ssl-certificate.json, step-templates/letsencrypt-selfhosted-http.json
- Marked existing step template as deprecated: **Lets Encrypt - Create SSL Certificate**
- Added new step template: **Lets Encrypt - Self-Hosted HTTP Challenge**
---
=> Lets Encrypt Step Template Changes

step-templates/wait.json
=> Variable to integer and output modification

step-templates/sql-fix-orphaned-user.json
New template to fix orphaned users when database restored from a different server.
---
=> New template for fixing orphaned users

step-templates/windows-apply-windows-updates.json
=> Adding Windows - Apply Windows Update template

step-templates/chocolatey-install-package.json
---
Fixes issue where attempts to install a package would fail claiming it couldn't extract the package to a system folder.
=> Bug chocolatey

step-templates/chocolatey-ensure-installed.json
---
_This is amending a currently existing step template._
To detect that Chocolatey exists on the machine `cinst.exe` is being tested for. `cinst` is an alias for `choco install` and _may_ be removed in future versions. To ensure that this template can be used in the future, and to improve reliability, change detection of `cinst.exe` to `choco.exe` (which exists in the same directory).
=> Increase future reliability and use choco.exe to ensure Chocolatey is installed 

step-templates/ftp-uploadfiles-packageparameter.json
---
- [X ] Parameter names should not start with `$`
=> Adding worker friendly version of FTP step using package parameter

step-templates/ftp-uploadfiles-packageparameter.json
---
Step template was previously merged, but we forgot to approve the manual intervention step so it was never deployed.
=> Adding ability to use Powershell module if WinSCP is not installed.

step-templates/chocolatey-install-package.json
* Added a `ChocolateySource` parameter to allow setting custom sources. This will help people set an internal source to get packages from;
* Add a `ChocolateyNoProgress` parameter. The step template currently has `choco` running and displaying the full download progress which can added hundreds / thousands of lines to the log. This allows that to be turned off (default is as per the previous version and turned on by default);
* Add a `ChocolateyOtherParameters` parameter which allows additional `choco` parameters to be added to the command line. `choco` has many parameters so this allows those to be used and the more popular ones specified as separate named parameters in the template.
- **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify …
=> (feat) Update Chocolatey Install step template with new parameters

step-templates/ssl-write-certificate-pem-and-key.json
- [x ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [x ] Parameter names should not start with `$`
- [x ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [x ] `LastModifiedBy` field must be present, …
=> SSL - Write Certificate Pem and Key to the Filesystem

step-templates/ssl-write-certificate-pem-and-key.json
- [] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
=> Add certificate variable as a parameter to the template

step-templates/chocolatey-manage-sources.json
This step template allows Chocolatey package sources to be managed.
=> (feat) Add step template to manage Chocolatey sources

step-templates/azure-web-app-slot-swap.json
Raised in comment found here: https://github.com/OctopusDeploy/Library/commit/c913f40e158f8d7261e5b3003f8e923760657500#commitcomment-41639347
=> corrected parameter name used

step-templates/oracle-add-user-to-role.json, step-templates/oracle-create-user-if-not-exists.json
=> Adding new oracle templates

step-templates/letsencrypt-dnsimple.json
Add new Step Template for Lets Enrcrypt using [DNSimple](https://dnsimple.com) Challenge for TLD, CNAME and Wildcard domains. 
- [] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
=> Add LetsEncrypt - DNSimple step template

step-templates/run-mabl-tests.json
=> run-mabl-tests step: added support for await completion flag

step-templates/pagerduty-close-maintenance-window.json, step-templates/pagerduty-open-maintenance-window.json
=> Updated PagerDuty steps to support v2 of the API

step-templates/testery-create-test-run.json, step-templates/testery-report-deployment.json
- [N/A] If a new `Category` has been created:
- [N/A] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
- [N/A] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it
=> Adding report deployment step template.

step-templates/microsoft-teams-post-a-message.json
Re line 40
#{Octopus.Web.DeploymentLink} evaluates to a value with a leading forward slash, so the `/` in the message body causes a double slash invalidating the URL to the deployment
* Do scripts in the template validate required arguments and fail by returning a non-zero exit code when things …
=> remove slash in message body to build correct URL

step-templates/microsoft-teams-post-a-message.json
When deploying to multiple tenants, all notifications are identical. This change adds the name of the tenant to the title of the notification, if it's a tenanted deployment.
Sample title (for a tenanted deployment):
Project 1,2,3 deployed to Production for Tenant
=> Include tenant name in message title for tenanted deployments

step-templates/epplus-register-dll-gac.json
=> Allow SecurityProtocol TLS, TLS 1.1 and TLS 1.2 for Invoke-WebRequest

step-templates/sql-create-database.json
---
Now allows you to select an Edition so you're in the desired pricing tier for Azure databases.
=> Adding ability to select Azure database edition for pricing tiers

spec/step-template-validation-tests.js, step-templates/aws-deploy-lambda.json, step-templates/azure-load-appsettings-from-file.json, step-templates/firebase-deploy.json, step-templates/flyway-info-bash.json, step-templates/flyway-info.json, step-templates/flyway-migrate-bash.json, step-templates/flyway-migrate-referenced-package.json, step-templates/ftp-uploadfiles-package.json, step-templates/liquibase-apply-changeset.json, step-templates/redgate-deploy-database-release-worker-friendly.json, step-templates/redgate-deploy-from-package-worker-friendly.json, step-templates/roundhouse-database-migration.json, step-templates/snowchange-deploy-scripts.json, step-templates/sql-deploy-dacpac-package-variable.json, step-templates/ssis-deploy-ispac-from-package-parameter.json, step-templates/ssrs-deploy-from-package-parameter.json
Fixes: https://github.com/OctopusDeploy/Issues/issues/6733
Summary: When a community step template defines a package feed id, if a use tries to copy this template in a non-default space, a validation error will most likely be produced since it is unlikely that the feed Id will exist in another users space. This includes using the default space default feed Id when in a non-default space.
Setting the package feed Id is not necessary, so this PR sets the package feed Ids in all templates where a variable is not used to null.
=> [Fix] Set Feed Ids to null to prevent validation error in non-default spaces

step-templates/iis-website-set-ip-security.json
The IP Security step is pretty slow when you have a large amount of IP rules. In my case, it takes ~32 seconds to process ~20 IP addresses. After the optimization, it takes ~32 seconds for the first configuration and ~5 seconds for subsequent configurations.
Before the modification, the step worked as follows:
1. Clear all IP rules
2. Call pretty expensive [Add-WebConfiguration](https://docs.microsoft.com/en-us/powershell/module/webadministration/add-webconfiguration?view=win10-ps) method _for each IP address_.
I modified the algorithm, and now it looks like this:
1. Get all existing rules from the IIS configuration
2. Compare IPs from the configuration and the step template.
3. Call pretty expensive [Add-WebConfiguration](https://docs.microsoft.com/en-us/powershell/module/webadministratio …
=> Optimize IIS set IP security step

step-templates/datadog-task-log.json
- [x ] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
- [x ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [ x] Parameter names should not start with `$`
- [x ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or …
=> Add datadog-task-log.json

step-templates/statuscake-maintenance-window.json
- [ X ] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
- [ X ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [ X ] Parameter names should not start with `$`
- [ X ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template …
=> Updated StatusCake step template to include help text

step-templates/octopus-register-listening-target.json
If tenanted only deployments is enabled and no tenants are passed in I've added a check and fail if this is the case. I've also added a check to see if the tenant list is null before it checks to find match tenants. This is to fix an issue whereby if no tenants are in the space then the script would bring all tenants back and select the first tenant in the list and associate that deployment target with the tenant.
=> Null tenant list issues

step-templates/flyway-database-migrations.json
=> Flyway execution containers

step-templates/azure-web-app-rolling-restart.json
This is a step template to perform a rolling restart of all instances in an Azure Web App.
=> Azure Web App delayed rolling restart step template

step-templates/liquibase-run-command.json
---
Fixes bug where you cannot install template because of missing DisplaySettings for liquibaseQuerystringParameters
=> Added missing DisplaySettings for querystring parameter.

step-templates/k8s-create-serviceaccount-and-target.json
---
As discussed in #1140 I had a need for adding annotations on the namespaces created by the Create Service Account and Target step template. While it was discussed to use Kustomize to facilitate this I ended up feeling that might be overkill for what I'm trying to achieve here. Honestly I don't think there's much more you would want to customize for a Kubernetes namespace except for annotations since it is fairly simple object.
Fixes #1140
=> Add support for putting annotations on namespaces

step-templates/venafi-tpp-revoke-oauth-token.json
Add new step template Venafi TPP - Revoke OAuth Token
It will revoke an access token obtained through a Venafi TPP instance using the VenafiPS PowerShell module's [Revoke-TppToken](https://venafips.readthedocs.io/en/latest/functions/Revoke-TppToken/) function.
---
**Required:** 
- The `VenafiPS` PowerShell module installed on the deployment target or worker. If the module can't be found, the step will attempt to download a version from the [PowerShell gallery](https://www.powershellgallery.com/packages/VenafiPS).
Notes:
- Tested on Octopus `2021.2`.
- Tested with VenafiPS `3.1.5`.
- Tested with both Windows PowerShell and PowerShell Core on Linux.
=> New step template - Venafi TPP - Revoke OAuth Token

step-templates/venafi-tpp-find-certificate-details.json
This step template will authenticate against a Venafi TPP instance using an existing OAuth access token, and find a matching certificate based on the certificate subject common name. This is achieved using a combination of two functions from the VenafiPS PowerShell module:
1. [Find-TppCertificate](https://venafips.readthedocs.io/en/latest/functions/Find-TppCertificate/) function.
2. [Get-VenafiCertificate](https://venafips.readthedocs.io/en/latest/functions/Get-VenafiCertificate/) function.
If multiple certificate matches are found, additional (optional) search criteria can be provided to further filter the results:
- Certificate serial number
- Full Issuer Distinguished Name (DN)
- Expires before
After any filtering is complete, if multiple matches are found, only the first certificate …
=> Add Venafi TPP - Find certificate details step template

step-templates/venafi-tpp-retrieve-certificate-details.json
Add new step template Venafi TPP - Retrieve Certificate Details
It will authenticate against a Venafi TPP instance using an existing OAuth access token, and retrieve a certificate's details using its Distinguished Name (DN). This is the absolute path to the certificate in the TPP instance.
This is achieved using the VenafiPS PowerShell module's  [Get-VenafiCertificate](https://venafips.readthedocs.io/en/latest/functions/Get-VenafiCertificate/) function.
You can also store the entire certificate result in `JSON` format in an [Octopus output variable](https://octopus.com/docs/projects/variables/output-variables)
This output variable can then be used in additional deployment or runbook steps.
On successful completion, you can also *optionally* revoke the access token used.
---
**Required:** …
=> New step template - Venafi TPP - retrieve certificate details

step-templates/venafi-tpp-export-certificate.json
This step template will authenticate against a Venafi TPP instance using an existing OAuth access token, and export a certificate using its Distinguished Name (DN). This is the absolute path to the certificate in the TPP instance.
This is achieved using the VenafiPS PowerShell module's [Export-VenafiCertificate](https://venafips.readthedocs.io/en/latest/functions/Export-VenafiCertificate/) function.
---
**Options:**
- Provide the distinguished name (DN) path to the certificate.
- Choose from the following export formats:
- `Base64`
- `Base64 (PKCS #8)`
- `DER`
- `JKS`
- `PKCS #7`
- `PKCS #12` 
- *Optional* - Provide a custom output path.
- *Optional* - Provide a custom output filename. If not supplied, the filename will automatically be taken from the response.
- *Optional* - Include the …
=> Add Venafi TPP Export certificate

step-templates/venafi-tpp-export-certificate.json, step-templates/venafi-tpp-import-certificate-into-octopus.json
Two changes:
1. New Step template **Venafi TPP - Import Certificate into Octopus**
2. Update to the existing template: **Venafi TPP - Export Certificate** - just to help text and descriptions (see commit 463e2df)
This step template will authenticate against a Venafi TPP instance using an existing OAuth access token, export a certificate by its Distinguished Name (DN), and then import the certificate into the Octopus certificate store.
The export is achieved using the VenafiPS PowerShell module's [Export-VenafiCertificate](https://venafips.readthedocs.io/en/latest/functions/Export-VenafiCertificate/) function.
---
**Export options:**
- Provide the distinguished name (DN) path to the certificate.
- Choose from the following export formats:
- `Base64`
- `Base64 (PKCS #8)`
- `DER`
- `PKCS …
=> New Venafi TPP - Import Certificate step + typo fix for Export cert step

step-templates/venafi-tpp-create-provision-certificate.json
This step template will authenticate against a Venafi TPP instance using an existing OAuth access token, and create a new certificate as well as optionally associate and push the new certificate to specified existing application(s). This is achieved using a combination of two functions from the VenafiPS PowerShell module:
1. [New-TppCertificate](https://venafips.readthedocs.io/en/latest/functions/New-TppCertificate/) function.
2. [Add-TppCertificateAssociation](https://venafips.readthedocs.io/en/latest/functions/Add-TppCertificateAssociation/) function.
---
**Options:**
- Provide a distinguished name (DN) path for the new certificate.
- Provide a name for the new certificate.
- Provide a common name (CN) for the new certificate.
- *Optional* - Provide the distinguished name (DN) path to a …
=> Add New Venafi TPP - Create/Provision Certificate step

step-templates/elmahio-notify-deployment.json
This is a minor addition to the existing step template to better control how to name the version when creating the deployment on elmah.io.
=> Added version field to better control how to name the version

step-templates/elmahio-upload-source-map.json
This is a new step template to upload a source map and minified JavaScript from Octopus deploy to elmah.io.
=> Step template to upload a source map and minified JavaScript to elmah.io

step-templates/block-progression.json
Small step template to block a release from progressing beyond the current environment.
=> New step template to block release progression

step-templates/variables-find-unreplaced.json
Updates `Variables - Find Unreplaced` to use `Write-Warning` instead of `$host.ui.WriteErrorLine`. Fixes #795
=> Update to Variables - Find Unreplaced step

step-templates/azure-web-app-disable-appoffline.json, step-templates/azure-web-app-enable-appoffline.json
Add two step templates:
1. **Azure Web App - Enable app_offline** 
2. **Azure Web App - Disable app_offline** 
The step templates either enable or disable the app_offline file. The enable step will take a provided app_offline file from a package and upload it to an Azure Web App to enable a way to safely bring down the app domain for a subsequent deployment.
The disable step does the reverse (removing the file)
Both requires a set of [deployment credentials](https://docs.microsoft.com/en-gb/azure/app-service/deploy-configure-credentials) for the Azure Web App.
**Required:** 
- Credentials with access to the [Kudu VFS API](https://github.com/projectkudu/kudu/wiki/REST-API#vfs)
Notes:
- Tested on Octopus `2021.2`.
- Tested with both Windows PowerShell and PowerShell Core on Linux.
=> Add Azure WebApp enable and disable app_offline steps

step-templates/microsoft-teams-post-a-message.json
Added a retry command to the **Microsoft Teams - Post a message** step template. Now when posting to MS teams, if configured, it will attempt up to 3 attempts.
=> Add retry command when posting to MS teams. Up to max 3 attempts

step-templates/aws-configure-lambda.json
Creates a new step template to allow users to create or update an existing lambda function using code hosted in S3 or as a container hosted in Amazon ECR.
=> Add the configure lambda function

web.config
Working with @chrisreeves- to add HTTP Headers to library.octopus.com
Has been tested on a blank website in Azure so that we're running against a real IIS server, but not with the full `library.` node app sitting underneath it, so we'll still need to do some testing against a proper instance to ensure everything is still working nicely.
=> Add HTTP Headers to improve security posture

web.config
This backs off the previously introduced CSP header and makes the values permissive 
enough to work with the current application code and page structure of the Library 
app. However, usage of `'unsafe-inline'` and `data:` are explicitly discouraged by the CSP
spec, because they are so permissive that it's like not having a CSP header at all.
We should do further analysis of the changes required to tighten up the CSP header
at a later date.
Also fixes the `Permissions-Policy` header to be in the right format, and disable almost
all known browser permissions - none should be relevant for our very simple Library app.
=> Loosen CSP headers to keep site working

step-templates/azure-install-windows-tentacle.json, step-templates/azure-linux-install-octopus-tentacle.json
Fix Azure tentacle templates with correct default value:
- `Azure Windows - Install Octopus Tentacle`
- `Azure Linux - Install Octopus Tentacle`
=> Fix Azure tentacle templates with correct default value

step-templates/json-validate-format-and-schema.json
=> Creation of the JSON validator

step-templates/mariadb-add-database-user-to-role.json, step-templates/mariadb-create-database.json, step-templates/mariadb-create-user.json
---
Fixes goofup by me to include Windows Auth.
=> Removing Windows Auth from mariadb

package-lock.json, package.json, step-templates/sql-create-database-enhanced.json, step-templates/sql-execute-sql-files.json
=> Adding new SQL Server templates.

server/views/index.pug
This PR adds google tag manager to the octopus Library [internal Slack thread for reference 🔒](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1658929201189609).  This adds google tag manager to all pages via the server index.pug with the following html
=> Adding google tag manager

step-templates/microsoft-teams-post-a-message.json
---
Adds `-UseBasicParsing` switch to avoid IE 8 engine.
=> Adding -UseBasicParsing

step-templates/sql-smo-create-login-and-user.json
---
This PR prefixes the step template variables names with `SMO_` so that they don't cause collisions with custom defined variables as mentioned on [this](https://g.octopushq.com/UserVariablesOverridingStepVariables) page.
__Note:__ this _might_ be a breaking change since the parameter names have changed combined with the fact that the parameters currently don't have a unique Id assigned. I've assigned them an Id as well to prevent this in the future.
=> Prefix step template variables to prevent collisions in SQL Server user/login provisioning step template

step-templates/liquibase-run-command.json
Add capturing the output of the Liquibase command to `LiquibaseCommandOutput` variable.
It may be useful when you want to use conditions in other steps.
Our use case is to run `liquibase status` command first, analyze the output, and the skip manual intervention step (and other Liquibase steps) if there are no changes.
=> Add capturing liquibase command output

gulpfile.babel.js, package-lock.json, package.json
I'm upgrading our build agents to our standardised docker-based agent pool. The environment is a little slimmer in those agents (no pre-installed python, etc). 
The current configuration using `node-sass` requires compilation of some machine-specific things during `npm install`/`npm ci`, which is both slow and creates dependencies on `python` and `vcc++` which are fairly annoying to resolve (and also creates assumptions about local devs' environments too). 
Given `node-sass` is deprecated, this PR updates us to use DartSass as the underlying Sass engine, which is under maintenance and doesn't incur the weird compilation stuff during `npm install`
Nothing about the dev process or the library.octopus.com site should change based on this PR.
PR includes an update of `package-lock.json`, …
=> Update gulp-sass and migrate from node-sass to dart-sass

.gitignore, tools/StepTemplatePacker/scripts/Get-OctopusStepTemplateFileType.ps1
Some steps are written in Python. And if you run `./tools/_unpack.ps1` the script throws an error
```
Unhandled script syntax 'Python'.
```
=> Add Python syntax support for unpacking

step-templates/sql-create-database-enhanced.json, step-templates/sql-create-database.json
This change adds the Azure SQL [Backup storage redundancy](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=azuresqldb-current&tabs=sqlpool#backup_storage_redundancy) option to the following step templates:
- SQL - Create Database If Not Exists
- SQL - Create Database If Not Exists Enhanced
For more info on the different redundancy options see [this](https://learn.microsoft.com/en-us/azure/azure-sql/database/automated-backups-overview?view=azuresql)
When using Azure, the default option if not specified is `GRS`. However, if you are not using Azure, then it can be left blank (that is the default in the steps as they are new parameters). 
Likewise, there are some Azure SQL database editions that don't support the premium backup storage redundancy …
=> Add Azure backup storage redundancy options to 2 create database steps

step-templates/sql-create-database.json
This PR updates the **SQL - Create Database If Not Exists** step template to add a retry attempts parameter and associated code to implement a retry (code inspired by the `Microsoft Teams - Post a message` step template).
The default is backward-compatible in that the value is set to 0 and not retry. If a non-integer based value is added for the parameter, no retries will be attempted either.
The context behind this change is to introduce a bit more resilience in the step so that transient errors like [this one in samples](https://samples.octopus.app/app#/Spaces-362/projects/pitstop-orchestration/deployments/releases/2023.01.11.11/deployments/Deployments-104584) can _hopefully_ just carry on.
=> Add retry attempts to create sql database

.github/CONTRIBUTING.md, package.json
This simplifies the "getting started" process for people contributing to the website.
Now you can just run `npm run setup` and you're ready to go.
=> Simplifies the getting started process.

step-templates/aws-execute-powershell.json
This PR fixes [this comment](https://github.com/OctopusDeploy/Library/issues/1358#issuecomment-1576127305) (but not the issue).
=> (fix) Remove choco alias

step-templates/mulesoft-cloudhub.json
=> Feed id not null

step-templates/sql-execute-sql-files.json
---
Added the new code, forgot the new parameter.
Adds the new parameter for forcing trust of the server certificate
No checkbox for trusting ceritificate
A new checkbox!
Fixes stupid mistake I made.
=> Forgot to add new paramater

step-templates/git-clone-copy-push-another-repo.json, step-templates/git-clone-copy-push-package.json, step-templates/git-clone-copy-push.json, step-templates/git-create-pull-request.json, step-templates/git-tag-repository.json
_Before submitting your PR, please delete everything above the line below._
---
These are new templates to help our Enterprise story.
Adding the ability to do different Git activities from within Octopus.
They didn't exist.
They do now!
Fixes the fact they didn't previously exist :)
=> Adding new git steps

step-templates/octopus-apply-octoterra-module-s3.json
This PR is a complement to the [Octopus - Serialize Project to Terraform](https://library.octopus.com/step-templates/e9526501-09d5-490f-ac3f-5079735fe041/actiontemplate-octopus-serialize-project-to-terraform) step and allows the Terraform module created by octoterra to be deployed. This step configures an S3 Terraform backend.
=> Octoterra Terraform Module Deployment Step

.octopus/deployment_process.ocl
Update process such that any pending manual intervention of the Slot Swap must be resolved before a new deployment can be started.
This is to prevent future occurrences of [a recent outage](https://status.octopus.com/incidents/f13s3jdp0znr) where conflicting deployments were run and took down `library.octopus.com`.
=> Prevent concurrent deployments

step-templates/octopus-create-octoterra-space-s3.json
This update fixes 2 issues:
1. Unable to save deployment process with step added
GoogleCloudAccount and AzureAcccount variables were set to 'true.' The fields are not exposed, so the user cannot set them to the "No" radio button for each one in the UI. 
Updated values to 'false.'
2. Unable to import/save as copy
There were two properties that existed but had empty string values: Package.PackageId and Package.FeedId. This caused a 'tiny types' error.
Removed the properties.
=> Fix to allow saving and save-as-copy

step-templates/octopus-add-runbook-to-project.json, step-templates/octopus-serialize-runbook-to-terraform.json
This PR defines a step that can be used to export a single runbook.
=> Added a step to export a single runbook

step-templates/octopus-add-runbook-to-project.json
Some tweaks to the default variables are required for this step to work with multiple runbook deployments:
* The workspace needs to be unique per space and project (not just per space)
* The default bucket key needs a prefix of `Runbooks_`
* Runbooks do not export any secret variables, so there is no need to define the file substitution feature
=> Tweak the add runbook ti project parameters

step-templates/readyroll-deploy-database-package.json
Customer reported issues when importing the step template into a Space ([private link](https://octopus.zendesk.com/agent/tickets/160235))
**Note:** Only the format of the step has been updated. The step is essentially a wrapper for Redgate's Ready Roll software. No testing has been performed to ensure the new step works with a Ready roll package.
The step can be imported
=> Update ReadyRoll template format to enable import in newer Octopus versions

step-templates/octopus-find-cac-updates.json
This PR adds a step that displays the differences between downstream and upstream CaC projects. This is part of the enterprise patterns strategy.
=> Added step to find updates between downstream and upstream projects

step-templates/octopus-add-runbook-to-project-azure.json, step-templates/octopus-apply-octoterra-module-azure.json, step-templates/octopus-create-octoterra-space-azure.json
This PR adds Azure versions of the octoterra terrafrom apply steps that currently exist for S3:
* Octopus - Create Octoterra Space (Azure Backend)
* Octopus - Populate Octoterra Space (Azure Backend)
* Octopus - Add Runbook to Project (Azure Backend)
=> Add Azure octoterra Terraform steps

step-templates/octopus-octolint-a-space.json
To create a step template Octopus users can use to run Octolint within their instance.
=> Add Octolint a Space step

.octopus/deployment_process.ocl
---
Fixing Octopus Library build process.
=> Update worker pool

.octopus/deployment_process.ocl, .octopus/schema_version.ocl
Updates to the deployment process for the library:
- Removed disabled slot steps that used AzureRM cmdlets
- Renamed slot steps to remove reference to az
- Disabled the WebDeploy step and enabled the new Azure App Service step
- Allow the staging slot clear step to run in parallel with the notification step at the start
- Updated the new step to mirror the old webdeploy step to use an execution container over bundled tooling
Previously the Azure App Service step timedout after ~100 seconds when deploying. This timeout has been increased, so it'd be a good test to see if this now works. If not, we can revert [that specific commit] (c4ae4cce00d32eeed84a3749a5105615bf974d0c)
=> Updates to Library deployment to use new azure app service step

.octopus/deployment_process.ocl
Summary of changes:
1. Updates the older (currently disabled WebDeploy) step that used to deploy the Library to Azure to rename it to highlight it did the deploy via WebDeploy
2. The new step used to have the name `(new App Service Step)` added to the end, this PR removes that.
3. Enables retries on the new Azure App Service step (a couple of deploys have resulted in `409 conflict`)
4. Updates the slugs for the steps
=> Rename old+new Library WebApp deploy steps and enable retries

step-templates/raygun-api-register-deployment.json, step-templates/raygun-register-deployment.json
BREAKING CHANGE
The existing Raygun step has not been updated since 2016 and is using a legacy API that appears to no longer be supported. 
Prior to this update, I was unable to get the action to work.
This has meant moving to using Personal Access Tokens & changing the Parameters passed to the step template.
I can update the PR to have this as a NEW step, however, given the existing isn't working updating the existing template felt acceptable.
Raygun API docs & Powershell example I've followed can be found here: https://raygun.com/documentation/product-guides/deployment-tracking/powershell/
=> Upgrade to use new Raygun API

app/components/TemplateItem.jsx, app/components/TemplateList.jsx, gulpfile.babel.js
We're looking at the loading time issue on library.octopus.com and think we can change the strategy for images to improve things.
This removes the inlining of images and instead refers to images on i.octopus.com.
The only templates affected are the Azure Load Balancer steps, which have specific logos rather than depending on categories.
The screenshot shows these specific images. We could create a category for these if necessary.
**Before** (production)
Server: 3,700 ms
Download: 2,370 ms
**After** (running in a GitHub code space)
Server: 483 ms
Download: 101 ms
=> Speed up library page

.gitignore, app/components/TemplateItem.jsx, app/components/TemplateList.jsx, gulpfile.babel.js
Octopus pulls data from the API in this project and it doesn't like the change to the Logo field.
Reverting changes to restore community step sync in Octopus.
=> Revert performance changes as it break API consumers

step-templates/application-insights-annotate-release-with-rbac.json
As Azure will stop supporting the function to annotate releases based on API keys and only supports RBAC to create annotations. There for I created this step template so an annotation can be created with a service principle.
Create an annotation with Azure CLI and Role-Based Access Control.
=> Add step template for creating an annotation in Azure Application Insights based on Azure CLI and RBAC instead of an API Key

step-templates/aws-deploy-lambda-image.json
---
This template implements the ability to deploy a lambda function using a docker image.  This is similar to [AWS - Configure Lambda Function](https://library.octopus.com/step-templates/db4f7564-1b04-41c6-a3a6-aca911236aee/actiontemplate-aws-configure-lambda-function), however, the new template allows you to use the package selector instead of the string based image uri.  In addition. it also implements the ENTRYPOINT and CMD override functionality AWS provides.
The deployment of a Lambda using a docker image.
The [AWS - Configure Lambda Function](https://library.octopus.com/step-templates/db4f7564-1b04-41c6-a3a6-aca911236aee/actiontemplate-aws-configure-lambda-function) template does not have the ability to use the package selector.  Modifying the [AWS - Configure Lambda …
=> Adding template to deploy image based Lamdbda functions

step-templates/argo-rollouts-status.json
---
This PR adds a new template that will get the status of an Argo Rollout.
It's new, all new, brand spanking new.
Template didn't exist.
A new, shiny, and exceptionally written template :P
=> Add argo rollout status

step-templates/argo-argocd-app-get.json, step-templates/argo-argocd-app-set-with-package.json, step-templates/argo-argocd-app-set.json, step-templates/argo-argocd-app-sync.json, step-templates/argo-argocd-app-wait.json
This PR introduces 5 new step templates:
1. Argo - argocd app get
2. Argo - argocd app set
3. Argo - argocd app set (with package)
4. Argo - argocd app sync
5. Argo - argocd app wait
=> Add ArgoCD cli step templates

step-templates/aspnetcore-set-environment-variable-iis.json
When using the `ASP.NET Core Set Environment Variables Via IIS Config` step template, it would incorrectly set the environment variable if it contained `=`
For example,
`ConnectionStrings__Default=Data Source=.;Initial Catalog=AppDB;`
Would set `ConnectionStrings__Default` to `Data Source` instead of `Data Source=.;Initial Catalog=AppDB;`
See the screenshot below,
This pull request updates the step template to split the string on the first `=`.
See the diff below,
```diff
@@ -32,9 +32,15 @@
Write-Host "---------------------------"
$appCmd = Join-Path $sev_appCmdPath 'appcmd.exe'
foreach($line in $sev_envVariables -split '\r?\n') {
-    $keyValuePair = $line -split '='
+    $indexOfEquals = $line.IndexOf('=')
+    if ($indexOfEquals -eq -1) {
+        Write-Host "Invalid environment …
```
=> Update aspnetcore-set-environment-variable-iis to support '='

step-templates/github-verify-attestation.json
=> Add Github - Verify Attestation

step-templates/tests/Invoke-PesterTests.ps1
**Background**
On a fresh clone of the repo, I was unable to run pester tests until I manually extracted them the scripts under test. There is some code in Invoke-PesterTests.ps1 that is _supposed_ to unpack any scripts under test, but it does not seem to work properly.
With this change, the code has been reorganized into 3 functions, `Import-Pester`, `Run-Tests` and `Unpack-Scripts-Under-Test`, with the code for `Unpack-Scripts-Under-Test` reworked the most to make it reliable.
**Pre-requisites**
[NA] Id should be a GUID that is not 00000000-0000-0000-0000-000000000000
NOTE If you are modifying an existing step template, please make sure that you do not modify the Id property (updating the Id will break the Library sync functionality in Octopus).
[NA] Version should be incremented, …
=> Unpack scripts under test automatically

step-templates/octopus-apply-octoterra-module-azure.json, step-templates/octopus-apply-octoterra-module-s3.json
Account parameters passed to Terraform steps must be resolved as Octostache templates rather than literal strings.
This PR fixes the AWS and Azure accounts passed to Terraform apply steps so they are correctly resolved.
=> Account variables must be octostache templates

step-templates/octopus-ai-prompt.json
This step allows Octopus to call the same AI service that backs the Copilot extension.
=> Added step to prompt the AI service

.github/workflows/Hyponome.yml
The GH Token generated will have permissions to comment on PRs from public forks as well as local PRs and should be safe as explained [here](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/)
=> Use `pull_request_target` instead of `pull_request`

step-templates/yams-upload.json
=> Removing broken link

step-templates/hockeyapp-upload-mobile-app.json
The markdown link has a leading space. This should be removed.
=> Remove space from link.

step-templates/microsoft-power-automate-post-adaptivecard.json
As far as I can tell from the Git History, this has never worked as the Variables in the script don't match the actual variables passed in
Script actually works now
=> Update microsoft-power-automate-post-adaptivecard to match variables used in step
